name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/installdep@v1
    - name: Install lv2-dev
      run: |
        sudo apt-get install lv2-dev
    - uses: actions/checkout@v1
    - name: make
      run: make
